service: dreamliner-backend-nest

custom:
  #  apigwBinary:
  #    types:
  #      - '/'
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  timeout: 30
  versionFunctions: false
  environment:
    STAGE: ${opt:stage, 'dev'}
    MY_API_KEY: secret_api_key
    DEV_DB_CONNECTION_STRING: mongodb+srv://dreamlinerentertainmentweb:TrhiAY3z0mkMlmaR@cluster0.ygqqpq9.mongodb.net/
    # DEV_DB_CONNECTION_STRING: mongodb+srv://devinfotechedge:23NX1Qn4XPFDPgQQ@cluster0.rk8tcob.mongodb.net/dreamliner?retryWrites=true&w=majority
    DEV_MONGO_DB_NAME: dreamliner
    PROD_DB_CONNECTION_STRING: mongodb+srv://dreamlinerentertainmentweb:TrhiAY3z0mkMlmaR@cluster0.ygqqpq9.mongodb.net/
    PROD_MONGO_DB_NAME: dreamliner_prod
    CLOUDFRONT_URL_DEV: https://dhoot28u2g2p5.cloudfront.net/
    CLOUDFRONT_URL_PROD: https://d8yc5z39mpthv.cloudfront.net/api

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

plugins:
  - serverless-offline
  # - serverless-apigw-binary
